// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uydwohxbfwgjxtvgatye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5ZHdvaHhiZndnanh0dmdhdHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Mzk2OTIsImV4cCI6MjA2NDQxNTY5Mn0.D7EAblpXnEgEL64ILhsGdbnwlV_UijSxmiPcm2ixs64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);